language: python
sudo: required
dist: xenial
services:
  - xvfb
notifications:
  email: false

cache: pip

# remember to remove 3.8 related workarounds below once
# 3.8 is released and wheels are available. Also change 3.8-dev to 3.8

addons:
  apt_packages:
    - pandoc
    - libhdf5-dev # remove once h5py is packaged for 3.8
    - gcc # this can go once we have scipy wheels for 3.8
    - gfortran # this can go once we have scipy wheels for 3.8
    - python-dev # this can go once we have scipy wheels for 3.8
    - libopenblas-dev # this can go once we have scipy wheels for 3.8
    - liblapack-dev # this can go once we have scipy wheels for 3.8

python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
  # whitelist

install:
    - pip install -r test_requirements.txt --upgrade --upgrade-strategy only-if-needed
    - pip install -e .

script:
    - mypy qdev-wrappers
    # check that line endings are correct avoiding mixed windows/unix style line endings
    - pylint --reports=n --disable=all --enable=mixed-line-endings,unexpected-line-ending-format --expected-line-ending-format=LF qdev-wrappers
